# Workflow derived from https://github.com/r-lib/actions/tree/master/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: test-coverage

jobs:
  test-coverage:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v1
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v1
        with:
          extra-packages: |
            covr
            sf
            weights
      - name: Test coverage
        run: |
          library(covr)
          options(covr.flags = c(CXXFLAGS = "-O2", LDFLAGS=""))
          Sys.setenv(NCRAN = TRUE, NMAC = TRUE)
          suppressWarnings(codecov(type = "all"))
          # codecov()
        shell: Rscript {0}
